In [4]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # to run all arguments and not just the last one
# https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

In [5]:
a = np.arange(15).reshape(3, 5)
a

a.shape
a.ndim
a.dtype.name
a.itemsize
a.size
type(a)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

(3, 5)

2

'int32'

4

15

numpy.ndarray

In [21]:
# Array creation
# call with a list of numbers instead of argument
# type of array can be explcitly called at runtime
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [23]:
# Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create 
# arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.
np.zeros( (3,4) )
np.ones( (2,3,4), dtype=np.int16 )  

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [27]:
# To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists
np.arange( 10, 30, 5 ) # what happens when array's are not in lists; literal items need to be added as lists
np.arange( 0, 2, 0.3 )

array([10, 15, 20, 25])

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [28]:
# it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:
np.linspace(0, 2, 9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [36]:
# Printing arrays
a = np.arange(6)
print(a)
b = np.arange(12).reshape(4, 3)
print(b)
c = np.arange(24).reshape(2, 3, 4) # 3D array
print(c) 
# if an array is too big, numpy prints only the corners; can be changed

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [42]:
# Basic operations
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
c
b**2
10*np.sin(a)

# * does an elementwise multiplication in numpy. to perform a matrix product, use dot or method
A = np.array([[1, 1],
             [0, 1]])
B = np.array([[2, 0],
             [3, 4]])
A*B                        # elementwise product
A.dot(B)                   # for matrix multiplication
np.dot(A, B)               # another way to get the matrix product

array([20, 29, 38, 47])

array([0, 1, 4, 9])

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

array([[2, 0],
       [0, 4]])

array([[5, 4],
       [3, 4]])

array([[5, 4],
       [3, 4]])

In [48]:
# Operators like += or *= act to modify the array instead of creating a new one.
a = np.ones((2, 3), dtype=int)
b = np.random.random((2, 3))
a *= 3 # changes all elements to 3
a
b += a
b      
a += b # b is not automatically converted to integer type; hence, an error

array([[3, 3, 3],
       [3, 3, 3]])

array([[ 3.84407723,  3.75479186,  3.52822733],
       [ 3.42429541,  3.67717701,  3.0318224 ]])

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [54]:
# When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one 
# (a behavior known as upcasting).
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
b.dtype.name
c = a+b
c
c.dtype.name
d = np.exp(c*1j)
d
d.dtype.name

'float64'

array([ 1.        ,  2.57079633,  4.14159265])

'float64'

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

'complex128'

In [9]:
# Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.
a = np.random.random((2, 3))
a
a.sum()
a.min()
a.max()

array([[ 0.06879589,  0.41409253,  0.30512429],
       [ 0.44057489,  0.03761608,  0.74208044]])

2.0082841190072269

0.037616084208113021

0.74208043666337087

In [10]:
# By default, these operations apply to the array like it was a list of numbers, regardless of its shape. 
# By specifying an axis, we can also apply an operation along a specific axis.
b = np.arange(12).reshape(3, 4)
b
b.sum(axis = 0)      # sum of each column
b.min(axis = 1)      # min of each row
b.cumsum(axis = 1)   # cumulative sum of each row

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([12, 15, 18, 21])

array([0, 4, 8])

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [17]:
# Univeral functions
B = np.arange(3)
B
np.exp(B)
np.sqrt(B)
C = np.array([2., -1., 4.])
np.add(B, C)

array([0, 1, 2])

array([ 1.        ,  2.71828183,  7.3890561 ])

array([ 0.        ,  1.        ,  1.41421356])

array([ 2.,  0.,  6.])

In [21]:
# Indexing, slicing and iterating
# One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
a = np.arange(10)**3
a
a[2]
a[2:5]
a[:6:2] = -1000
a
a[ : :-1]
for i in a:
    print(i**(1/3.))
    
# Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:
def f(x, y):
    return 10*x+y
b = np.fromfunction(f, (5,4), dtype = int)
b
b[2, 3]      
b[0:5, 1]    # each row in the 2nd column of b
b[ : , 1]    # equivalent to the previous example
b[1:3, : ]   # each column in the 2nd and 3rd row of b
b[-1]        # the last row; equivalent to b[-1, :]; can also be written as b[-1,...]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

8

array([ 8, 27, 64], dtype=int32)

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729], dtype=int32)

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000], dtype=int32)

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


C:\Users\309292\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\__main__.py:11: RuntimeWarning: invalid value encountered in power


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

23

array([ 1, 11, 21, 31, 41])

array([ 1, 11, 21, 31, 41])

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

array([40, 41, 42, 43])

array([40, 41, 42, 43])

In [24]:
# the dots represent as many colons needed to produce a complete indexing tuple so if x is a 5 rank array(has 5 axes),
# then x[1,2,...] is equivalent to x[1,2,:,:,:]
c = np.array([[[0, 1, 2],
              [10, 12, 13]],
             [[100, 101, 102],
             [110, 112, 113]]])
c.shape
c[1,...]
c[...,2]
for row in b:
    print(row)

(2, 2, 3)

array([[100, 101, 102],
       [110, 112, 113]])

array([[  2,  13],
       [102, 113]])

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
